development:
  fluent_host:   '10.1.0.11'
  fluent_port:   24224
  tag:           'shop'
  messages_type: 'string'

test:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'shop'
  messages_type: 'string'

production:
  fluent_host:   '127.0.0.1'
  fluent_port:   24224
  tag:           'shop'
  messages_type: 'string'